services:
  apetavern-proxy:
    image: nginx:latest
    container_name: apetavern-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/webserver.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/webroot
      - ./error:/var/www/error
  apetavern-app:
    build:
      context: .
    container_name: apetavern-app
    restart: unless-stopped
    command: npm run dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules